services:

  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=inmobiliaria
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5555:5432"